minimumReleaseAge: 0
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vitest: 4.1.10
  vite-plus: 0.2.7
  "@vitest/coverage-v8": 4.1.10
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"
